# Generated by Django 4.2.2 on 2023-06-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureNestApp', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
