# Generated by Django 4.2.2 on 2023-06-12 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecureNestApp', '0006_alter_message_date_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='loginid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
