# Generated by Django 4.2.2 on 2023-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureNestApp', '0008_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actname', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
