# Generated by Django 4.2.2 on 2023-06-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecureNestApp', '0011_policestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('station', models.CharField(max_length=100, null=True)),
                ('reply', models.CharField(default='NO REPLY', max_length=500)),
                ('status', models.CharField(default='RAISED', max_length=100)),
                ('childid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureNestApp.child')),
            ],
        ),
    ]
