# Generated by Django 4.2.2 on 2023-06-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureNestApp', '0012_alter_child_phone_alter_school_phone_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
