# Generated by Django 4.2.2 on 2023-06-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureNestApp', '0014_alter_complaints_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='policeReply',
            field=models.CharField(default='NO REPLY', max_length=500),
        ),
    ]
