# Generated by Django 4.2.2 on 2023-06-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecureNestApp', '0017_complaints_utype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('reply', models.CharField(default='NO REPLY', max_length=500)),
                ('policeReply', models.CharField(default='NO REPLY', max_length=500)),
                ('status', models.CharField(default='RAISED', max_length=100)),
                ('schoolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureNestApp.school')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SecureNestApp.policestation')),
            ],
        ),
    ]
